### ISSUE TITLE
Model Weights?

### ISSUE THREAD

**Issue by logan-markewich** [LaotechLabs/LOGOS#3]
Are you able to share a link to the weights of your fine-tuned model?

**Comment by maitridas** [comment]
Hi, You can now find the links for the weights in the readme. Also have updated the links in inference.ipynb you can directly download the weights from the notebook if you want.

**Comment by logan-markewich** [comment]
Thanks for updating the readme and notebook! That helps a ton. (also, crazy fast response lol)

💪🏻 👍🏻
